# Test configuration for ddup
interval: 10s # Faster interval for testing

# Test endpoints using public services
endpoints:
  - name: "google-dns"
    url: "https://dns.google/resolve?name=google.com&type=A"
    ip: "8.8.8.8"
    timeout: "3s"
  - name: "cloudflare-dns"
    url: "https://cloudflare-dns.com/dns-query?name=cloudflare.com&type=A"
    ip: "1.1.1.1"
    timeout: "3s"
  - name: "httpbin"
    url: "https://httpbin.org/status/200"
    ip: "54.230.100.1"
    timeout: "3s"

# DNS Provider Configuration (for testing - use fake values)
dns:
  provider: "cloudflare"
  cloudflare:
    apiToken: "fake-token-for-testing"
    zoneId: "fake-zone-id"
    recordName: "test.example.com"
    recordType: "A"
    ttl: 300
