# Health Check and DNS Update Configuration

# How often to perform health checks
interval: 30s

# List of domains to manage
domains:
  - recordName: "service.example.com"
    provider: "example-provider-1"
    ttl: 120
    endpoints:
      - name: "server1"
        url: "http://192.168.1.100:8080/health"
        ip: "192.168.1.100"
        timeout: "5s"
      - name: "server2"
        url: "http://192.168.1.101:8080/health"
        ip: "192.168.1.101"
        timeout: "5s"
  - recordName: "foo.example.com"
    provider: "example-provider-1"
    ttl: 120
    endpoints:
      - name: "foo1"
        url: "http://192.168.1.200:9000/health"
        ip: "192.168.1.200"
        timeout: "5s"
      - name: "foo2"
        url: "http://192.168.1.201:9000/health"
        ip: "192.168.1.201"
        timeout: "5s"

# Provider Configuration
providers:
  example-provider-1:
    cloudflare:
      apiToken: "your-cloudflare-api-token"
      zoneId: "your-zone-id"
