# Health Check and DNS Update Configuration

# How often to perform health checks
interval: 30s

# List of domains to manage
domains:
  - recordName: "service.example.com"
    provider: "example-provider-1"
    ttl: 120
    healthChecks:
      timeout: "2s"
      attempts: 3
    endpoints:
      - name: "server1"
        url: "http://192.168.1.100:8080/health"
        ip: "192.168.1.100"
      - name: "server2"
        url: "http://192.168.1.101:8080/health"
        ip: "192.168.1.101"
  - recordName: "foo.example.com"
    provider: "example-provider-1"
    ttl: 120
    healthChecks:
      timeout: "5s"
      attempts: 2
    endpoints:
      - name: "foo1"
        url: "http://192.168.1.200:9000/health"
        ip: "192.168.1.200"
      - name: "foo2"
        url: "http://192.168.1.201:9000/health"
        ip: "192.168.1.201"

# Provider Configuration
providers:
  example-provider-1:
    cloudflare:
      apiToken: "your-cloudflare-api-token"
      zoneId: "your-zone-id"
